### ISSUE TITLE
[EPIC] Use Solr for search in DGU Find

### ISSUE THREAD

**Issue by kentsanggds** [alphagov/datagovuk_find#1293]
Add Solr Gem to find as a feature so can switch between Opensearch and Solr

```[tasklist]
### Search results page
- [x] https://github.com/alphagov/datagovuk_find/issues/1318
- [ ] https://github.com/alphagov/datagovuk_find/pull/1337
- [ ] https://github.com/alphagov/datagovuk_find/issues/1335
- [ ] https://github.com/alphagov/datagovuk_find/pull/1344
- [x] Don’t clear search keywords when filters are applied
- [x] Fix removing filters
- [ ] https://github.com/alphagov/datagovuk_find/issues/1336
- [ ] https://github.com/alphagov/datagovuk_find/issues/1354
- [ ] https://github.com/alphagov/datagovuk_find/pull/1365
- [x] Prevent XSS: sanitise input (done by rails), use strong params (not needed)
- [ ] https://github.com/alphagov/datagovuk_find/pull/1368
- [ ] https://github.com/alphagov/datagovuk_find/issues/1339
- [ ] https://github.com/alphagov/datagovuk_find/issues/1340
- [x] Add handling for `RSolr::Error::Http - 400 Bad Request` error when invalid term is entered e.g. -
- [x] Scope Publisher filter to returned datasets (TIMEBOX) - this only works when searching by keywords
- [ ] Show Availability for unreleased datasets (TIMEBOX, post launch)
- [x] (WON'T DO) Escape special Solr characters in query
- [ ] https://github.com/alphagov/datagovuk_find/pull/1378
- [ ] https://github.com/alphagov/datagovuk_find/pull/1388
```

```[tasklist]
### Individual dataset page
- [x] https://github.com/alphagov/datagovuk_find/issues/1316
- [ ] https://github.com/alphagov/datagovuk_find/pull/1359
- [ ] https://github.com/alphagov/datagovuk_find/issues/1327
- [ ] https://github.com/alphagov/datagovuk_find/issues/1317
- [x] Handle 'Not found' datasets e.g. /3c0d0074-05a3-491a-a144-89ea54654d47/aberdeen-city
- [x] Issue rendering /dataset/solr/41600666-30dc-4243-9b64-4be3e8f5c65f/spend-over-f25-000-in-2gether-nhs-foundation-trust (not in integration)
- [x] Legacy datasets - they will work when we switch over, it's a redirect
- [ ] https://github.com/alphagov/datagovuk_find/pull/1387
- [x] Review OpenSearch tests for any edge cases
- [ ] (NOT NOW) Formats should be derived e.g. /562eb38e-387a-440d-bc61-c7cb7e927fba/coastal-physiographic-features-barrier-beach (https://github.com/ckan/ckan/pull/1350)
- [ ] (NOT NOW) Tests are slow and difficult to extend. WIP: https://github.com/alphagov/datagovuk_find/compare/main-solr...solr-use-factories-for-testing, basic dataset factory added since then for unit tests
```

```[tasklist]
### Testing, pre-launch tasks
- [ ] https://github.com/alphagov/datagovuk_find/issues/1348
- [x] Errors appear in logs (Kibana)
- [x] Check Solr performance and carry out load testing
- [x] Manually test popular URLs https://lookerstudio.google.com/u/0/reporting/1dLIysu5Ie131ZL3gGT7zyWBhffNgTSX2/page/cdu
- [x] Errors appear in Sentry
- [ ] https://github.com/alphagov/datagovuk_find/pull/1386
- [x] Double check that all indexes are available in production (for orgs)
- [x] Update routes, controllers and views to switch it over to Solr
- [x] ~Comms, scheduled maintenance?~
- [x] Add a note to DGU documentation + /support page
- [ ] https://github.com/alphagov/datagovuk_find/pull/1404
- [ ] https://github.com/alphagov/datagovuk_find/pull/1398
```

```[tasklist]
### Post launch fixes
- [ ] https://github.com/alphagov/datagovuk_find/pull/1407
- [ ] https://github.com/alphagov/datagovuk_find/pull/1405
- [ ] https://github.com/alphagov/datagovuk_find/pull/1402
- [ ] https://github.com/alphagov/datagovuk_find/pull/1401
- [ ] https://github.com/alphagov/datagovuk_find/pull/1400
- [ ] https://github.com/alphagov/datagovuk_find/pull/1397
- [ ] https://github.com/alphagov/datagovuk_find/pull/1396
- [ ] https://github.com/alphagov/datagovuk_find/pull/1395
- [ ] https://github.com/alphagov/datagovuk_find/pull/1394
```

```[tasklist]
### Post launch
- [x] Remove OpenSearch from Find codebase
- [ ] Retire Publish https://docs.publishing.service.gov.uk/manual/retiring-an-application.html
- [x] Remove OpenSearch from infrastructure
- [x] Update architecture diagrams and docs
```

**Comment by kentsanggds** [comment]
We had a chat about how to proceed with progressing and reviewing the work in smaller chunks. 

Proposal is to create another branch `main-update` from which other update branches will be fed into. This will ensure that smaller PRs can be reviewed and merged into it without affecting any deployments to production. 

The inteegration cluster can be updated to point to commits on this branch specifically when there is a need to deploy things for testing on EKS.

As there is generally very little development on the Find application I don't forsee any issues around the branch drifting from the `main` branch.
