### ISSUE TITLE
Add dataset's datafile preview page using Solr

### ISSUE THREAD

**Issue by deborahchua** [alphagov/datagovuk_find#1317]
This option is only available if the datafile is a CSV or organogram. It will linked to from the list of datafiles on the dataset page.

It depends on https://github.com/alphagov/datagovuk_find/issues/1316

```[tasklist]
### Tasks
- [ ] Add basic preview page
- [ ] Show CSV preview
- [ ] Show organogram preview and download button - this will only be shown if the datafile is an organogram. This is determined by whether the `schema_id` is available and matches one of the listed ID
- [ ] Map reviews?
```

**Comment by AgaDufrat** [comment]
Examples:

Organagram: https://www.data.gov.uk/dataset/5af9a3c5-fddb-4e5d-81f3-4bdfc6699f55/organogram-of-staff-roles-and-salaries-for-ifate-june-2023/datafile/2e75d92a-c618-418d-9ea1-689c683ffeb5/preview
